/*
 * LHSR Daemon - Config file parsing
 *
 * Parses /etc/lhsr/lhsrd.conf in simple key=value format.
 * Lines starting with '#' or ';' are comments.
 * Blank lines are ignored.
 *
 * Supported keys:
 *   smart_poll_interval = <seconds>
 *   error_threshold     = <count>
 *   auto_failover       = <0|1>
 *   notify_on_fail      = <0|1>
 *   verbose             = <0|1>
 *
 * Copyright (C) 2026 LHSR Team
 * License: GPLv3
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <syslog.h>

#include "lhsrd.h"

#define LINE_MAX 1024

/* Set defaults before parsing */
void lhsr_config_defaults(struct daemon_config *cfg)
{
	cfg->smart_poll_interval = 300;
	cfg->error_threshold     = 3;
	cfg->auto_failover       = 1;
	cfg->notify_on_fail      = 1;
	cfg->verbose             = 0;
}

/*
 * Trim leading and trailing whitespace in-place.
 */
static char *trim(char *s)
{
	char *end;

	while (isspace((unsigned char)*s))
		s++;
	if (*s == '\0')
		return s;

	end = s + strlen(s) - 1;
	while (end > s && isspace((unsigned char)*end))
		end--;
	*(end + 1) = '\0';
	return s;
}

int lhsr_config_load(struct daemon_config *cfg, const char *path)
{
	FILE *f;
	char line[LINE_MAX];
	int lineno = 0;

	/* Start with defaults */
	lhsr_config_defaults(cfg);

	f = fopen(path, "r");
	if (!f) {
		/* File missing is not an error — use defaults */
		syslog(LOG_INFO, "No config file at %s, using defaults", path);
		return 0;
	}

	while (fgets(line, sizeof(line), f)) {
		char *p, *key, *val;

		lineno++;

		/* Strip trailing newline */
		p = line + strlen(line);
		if (p > line && *(p - 1) == '\n')
			*(p - 1) = '\0';

		p = trim(line);

		/* Skip blank lines and comments */
		if (*p == '\0' || *p == '#' || *p == ';')
			continue;

		/* Split on '=' */
		key = p;
		val = strchr(p, '=');
		if (!val) {
			syslog(LOG_WARNING, "%s:%d: ignoring malformed line (no '=')", path, lineno);
			continue;
		}
		*val++ = '\0';
		key = trim(key);
		val = trim(val);

		if (strcasecmp(key, "smart_poll_interval") == 0) {
			cfg->smart_poll_interval = atoi(val);
		} else if (strcasecmp(key, "error_threshold") == 0) {
			cfg->error_threshold = atoi(val);
		} else if (strcasecmp(key, "auto_failover") == 0) {
			cfg->auto_failover = atoi(val) != 0;
		} else if (strcasecmp(key, "notify_on_fail") == 0) {
			cfg->notify_on_fail = atoi(val) != 0;
		} else if (strcasecmp(key, "verbose") == 0) {
			cfg->verbose = atoi(val) != 0;
		} else {
			syslog(LOG_WARNING, "%s:%d: unknown key '%s'", path, lineno, key);
		}
	}

	fclose(f);
	syslog(LOG_INFO, "Loaded config from %s (%d lines)", path, lineno);
	return 0;
}

int lhsr_config_save(const struct daemon_config *cfg, const char *path)
{
	FILE *f;

	f = fopen(path, "w");
	if (!f) {
		syslog(LOG_ERR, "Cannot write config to %s: %m", path);
		return -1;
	}

	fprintf(f, "# LHSR Daemon Configuration\n");
	fprintf(f, "# Generated by lhsrd\n\n");
	fprintf(f, "smart_poll_interval = %d\n", cfg->smart_poll_interval);
	fprintf(f, "error_threshold     = %d\n", cfg->error_threshold);
	fprintf(f, "auto_failover       = %d\n", cfg->auto_failover);
	fprintf(f, "notify_on_fail      = %d\n", cfg->notify_on_fail);
	fprintf(f, "verbose             = %d\n", cfg->verbose);

	fclose(f);
	return 0;
}
